name: SpawnerPickaxeX
version: ${project.version}
main: me.c10coding.spawnerpickaxex.SpawnerPickaxeX
commands:
  spawnerpickaxex:
    aliases:
      - spx
    permission-message: "You do not have permission to use that command!"
permissions:
  spx.give:
    default: op
    description: "Allows players to give out SpawnerPickaxes"
